server:
  port: 6003
spring:
  application:
    name: org-hystrix-consumer-6003
eureka:
  instance:
    hostname: localhost
    instance-id: org-hystrix-consumer-6003
    prefer-ip-address: true
#    lease-renewal-interval-in-seconds: 1
#    lease-expiration-duration-in-seconds: 2
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      defaultZone: http://eureka7001.com:7001/eureka
feign:
  hystrix:
    enabled: true
