server:
  port: 7777
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: test-001
          uri: lb://org
          predicates:
            - Path=/org/get/**
            - After=2020-11-24T19:42:33.081+08:00[Asia/Shanghai]
      discovery:
        locator:
          enabled: true

eureka:
  instance:
    hostname: localhost
    instance-id: gateway-7777
    prefer-ip-address: true
  #    lease-renewal-interval-in-seconds: 1
  #    lease-expiration-duration-in-seconds: 2
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      defaultZone: http://eureka7001.com:7001/eureka
